# Generated by Django 2.2.24 on 2021-11-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronasolos', '0001_initial'),
        ('people', '0033_set_contributors_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acessolattes',
            field=models.URLField(blank=True, help_text='Link de acesso ao currículo Lattes do pesquisador', max_length=300, null=True, verbose_name='Currículo Lattes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='datahoraatualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='datanascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emailsecond',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email secundário'),
        ),
        migrations.AddField(
            model_name='profile',
            name='formacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_inst', to='pronasolos.Instituicao', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, help_text='Open Researcher and Contributor ID', max_length=100, null=True, verbose_name='ORCiD'),
        ),
        migrations.AddField(
            model_name='profile',
            name='perfil',
            field=models.CharField(blank=True, choices=[('colaborador', 'Colaborador/Pesquisador'), ('curadoria', 'Curadoria'), ('administrador', 'Administrador Regional'), ('comiteexecutivo', 'Comitê Executivo'), ('comiteestrategico', 'Comitê Estratégico'), ('superusuario', 'Super Usuário')], default='colaborador', max_length=20, null=True, verbose_name='Perfil do Usuário'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userinteresse',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_areainteresse', to='pronasolos.AreaInteresse', verbose_name='Temáticas de Interesse'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userregiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_regiao', to='pronasolos.Regiao', verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='profile',
            name='useruf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_uf', to='pronasolos.Unidade_Federacao', verbose_name='Estado'),
        ),
    ]
