# Generated by Django 2.2.24 on 2021-11-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_auto_20211128_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='datahoraatualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
