# Generated by Django 2.2.24 on 2021-11-28 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronasolos', '0002_auto_20211128_2338'),
        ('base', '0060_auto_20210512_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='project_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_projeto', to='pronasolos.Projeto', verbose_name='Projeto relacionado'),
        ),
    ]
