# Generated by Django 2.2.24 on 2021-11-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronasolos', '0004_unidade_federacao_regiao'),
        ('documents', '0031_auto_20201107_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_projeto', to='pronasolos.Projeto'),
        ),
    ]
